In [2]:
import numpy as np
import pandas as pd
from matplotlib.pyplot import subplots
import statsmodels.api as sm
from statsmodels.stats.outliers_influence \
 import variance_inflation_factor as VIF
from statsmodels.stats.anova import anova_lm
from ISLP import load_data
from ISLP.models import (ModelSpec as MS,
 summarize,
 poly)

In [3]:
rng = np.random.default_rng(1)
x = rng.normal(size=100)
y = 2 * x + rng.normal(size=100)

In [5]:
model = sm.OLS(y, x)
results = model.fit()
summarize(results)

      coef  std err       t  P>|t|
x1  1.9762    0.117  16.898    0.0

In [6]:
# We can strongly reject the null hypothesis as t is very large and P is 0

In [7]:
model = sm.OLS(x, y)
results1 = model.fit()
summarize(results1)

      coef  std err       t  P>|t|
x1  0.3757    0.022  16.898    0.0

Result a give a slope close to 2 which is the relationship y/x without noise. Result b gives x/y which is close to 1/2 without noise